server:
  port: 8888
  address: 192.168.200.128

mybatis:
  type-aliases-package: com.chenkr.demo.pojo

spring:
  redis:
    host: localhost
    port: 6379
    password: sswadff5201314
    database: 101
    jedis:
      pool:
        max-active: 128
        max-idle: 256
        max-wait: -1ms
        min-idle: 0

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: Asatos
    password: sswadff5201314
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.200.1:3306/music_db
  jpa:
    show-sql: true
    database: mysql


debug: false
